EMMROSE/gom

- Gemfile
- Gemfile.lock
- app/controllers/activities_controller.rb
- app/models/activity.rb
- test/controllers/activities_controller_test.rb
creating controller for activities and adding index action with search (gem PG SEARCH)
> adding controller activities & index

- app/views/activities/index.html.erb
adding views of activities#index
> adding views of activities#index

- app/controllers/activities_controller.rb
- app/controllers/sessions_controller.rb
- app/views/sessions/index.html.erb
- test/controllers/sessions_controller_test.rb
skip authentification for index and show for sessions and acivities
> Added controller/view of sessions, skip_authentifictation

- Gemfile
- Gemfile.lock
- app/controllers/activities_controller.rb
- app/models/session.rb
- config/initializers/geocoder.rb
- db/migrate/20200225094410_add_coordinates_to_session.rb
- db/schema.rb
adding geocoder gem and update research in controller
> geocoder & map

- config/initializers/geocoder.rb
> geocode settings

- Gemfile
- Gemfile.lock
- app/controllers/activities_controller.rb
- app/models/activity.rb
- app/models/sport_session.rb
- app/models/user.rb
- app/views/activities/index.html.erb
- config/environments/development.rb
- config/storage.yml
- db/migrate/20200225130208_create_active_storage_tables.active_storage.rb
- db/schema.rb
- db/seeds.rb
integrate Cloudinary, uploaded pictures for activities seeds
> Done setup and photo seeds for activity

- app/controllers/dashboards_controller.rb
- app/models/user.rb
- app/views/dashboards/dashboard.html.erb
- app/views/shared/_navbar.html.erb
- config/routes.rb
- db/seeds.rb
Hi Guys, 
PLease review and merge.
Many thanks 
Othmane
> New dashboard

- app/assets/stylesheets/components/_banner.scss
- app/assets/stylesheets/components/_navbar.scss
- app/views/sport_sessions/index.html.erb
> Aligned search and btn

- app/controllers/dashboards_controller.rb
- app/controllers/session_users_controller.rb
- app/views/dashboards/dashboard.html.erb
- config/routes.rb
> add "owned sessions" on dashboard
> add option to accept/reject requests on dashboard
> create "accept" route and controller method to change session_users status from 'pending' to 'accepted'
> create "reject" route and controller method to change session_users status from 'pending' to 'rejected'
> Add accepting and rejecting sport session requests from dashboard

- app/views/shared/_banner.html.erb
- app/views/shared/_navbar.html.erb
modifying text align for input into banner and navbar
> input research aligned at left

- app/controllers/sport_sessions_controller.rb
- app/views/sport_sessions/_info_window.html.erb
- app/views/sport_sessions/index.html.erb
Added links to both small-cards and info-window(map)
Updated Devise to authenticate user for sport_session_show
> Added links to sport_sessions/id

- app/assets/stylesheets/components/_card.scss
- app/controllers/activities_controller.rb
- app/views/activities/index.html.erb
- db/seeds.rb
Added a sport_session7 in the seeds to test
Structured activities#index and added the count of sessions to come
> Added structure

- app/controllers/sport_sessions_controller.rb
- app/views/shared/_navbar.html.erb
adding a research to navbar with tag select.
setting of index into sport_sessions controller
> research by activity and location

- app/assets/stylesheets/components/_chat.scss
- app/channels/sport_session_channel.rb
- app/controllers/chatrooms_controller.rb
- app/controllers/messages_controller.rb
- app/controllers/sport_sessions_controller.rb
- app/javascript/channels/sportSession_channel.js
- app/javascript/channels/sport_session_channel.js
- app/javascript/packs/application.js
- app/models/chatroom.rb
- app/models/message.rb
- app/models/sport_session.rb
- app/models/user.rb
- app/views/shared/_message.html.erb
- app/views/sport_sessions/show.html.erb
- config/routes.rb
- db/migrate/20200227110658_drop_table.rb
- db/migrate/20200227111305_add_sport_session_column_to_messages.rb
- db/schema.rb
- db/seeds.rb
- test/channels/sport_session_channel_test.rb
- test/controllers/chatrooms_controller_test.rb
- test/models/chatroom_test.rb
> Dropped chatroom

- app/controllers/sport_sessions_controller.rb
- app/javascript/packs/application.js
- app/javascript/plugins/init_autocomplete.js
- app/views/shared/_navbar.html.erb
- app/views/sport_sessions/index.html.erb
- app/views/sport_sessions/new.html.erb
- db/seeds.rb
- Added autocomplete on SS#new
- link_to create_session on the dashboard
> Fixed seeds, add autocomplete

- app/assets/stylesheets/pages/_dashboard.scss
- app/views/dashboards/dashboard.html.erb
adjusted style to dashboard.
Many thanks
> ajusted style to dashboard

- app/javascript/plugins/flatpickr.js
> Fix flatpickr

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/pages/_dashboard.scss
- app/javascript/components/dashboard.js
- app/javascript/packs/application.js
- app/views/dashboards/dashboard.html.erb
- app/views/layouts/application.html.erb
Smooth scrolling working fine on Dashboard now, without the need to add some extra margin tops to the elements (using JS)
> Solve smooth scrolling on dashboard

- app/assets/stylesheets/components/_calendar.scss
- app/assets/stylesheets/components/_form.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_sport_session_creation_modal.scss
- app/javascript/components/form.js
- app/views/layouts/application.html.erb
- app/views/shared/_navbar.html.erb
- app/views/shared/_sport_session_creation_modal.html.erb
- app/views/sport_sessions/new.html.erb
**!!! Don't merge this one for now... Need to ask a TA the correct way to add a modal on every pages**
> Add text info for level and capacity
> Improve JS
> Put the sport session creation form in a modal accessible from every pages
> Improve sport session creation form + put it as a modal

- app/assets/stylesheets/components/_filters.scss
- app/views/shared/_navbar.html.erb
- app/views/shared/_search_filters.html.erb
- app/views/sport_sessions/index.html.erb
- When a filter is selected it goes grey with an hover effect on the X to remove it
> improve front design of selected filters

- app/assets/stylesheets/pages/_dashboard.scss
- app/views/dashboards/dashboard.html.erb
pls review/merge.
Many thanks 
OL
> sess in order + style

- app/assets/stylesheets/application.scss
- app/javascript/plugins/init_mapbox.js
> adding a zoom to map

- app/assets/stylesheets/components/_map.scss
- app/views/sport_sessions/_info_window.html.erb
modify flash info window with :+1: 
a new withd and a new height
adding a picture according to sport activity
to do : 
review info details font and how to display that.
> modify flash window infos

- app/controllers/dashboards_controller.rb
pls merge this one asap
merci
OL
> minor debug on dashboard controller

- app/assets/stylesheets/pages/_dashboard.scss
- app/views/dashboards/dashboard.html.erb
please review / merge 
Many thanks 
OL
> more icons

- app/assets/stylesheets/components/_form.scss
- app/views/shared/_sport_session_creation_modal.html.erb
Create button full width, bottom position + more readable level gauge
pls review / merge 
Many thanks 
OL
> new session form enhancements

- app/javascript/plugins/init_mapbox.js
> new map style

- app/assets/stylesheets/components/_form.scss
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
change form for sign in and sign up
> signup form

- app/javascript/plugins/init_mapbox.js
delete relief layout from initmapbox
> delete relief layout for initmap

- app/assets/stylesheets/components/_form.scss
- app/controllers/application_controller.rb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/devise/shared/_links.html.erb
- app/views/layouts/application.html.erb
- app/views/shared/_login_modal.html.erb
- app/views/shared/_navbar.html.erb
- app/views/shared/_signup_modal.html.erb
adding a modal for signup and login
> Background login

- app/assets/stylesheets/components/_sport_session_card.scss
- app/views/sport_sessions/show.html.erb
changing display for info on card 
grow card
adding a min width for chat content
to do : pending button and reject
> Modifying show sportsession

- app/javascript/plugins/flatpickr.js
- db/seeds.rb
Need to dbug calendar in creation form (check the JS)
> Updated seeds and debug dashb-calendar

- app/assets/stylesheets/components/_form.scss
- app/views/shared/_sport_session_creation_modal.html.erb
> added labels to the form

- app/assets/stylesheets/components/_chat.scss
- app/assets/stylesheets/components/_sport_session_card.scss
- app/views/sport_sessions/show.html.erb
change arrow direction for level bar
> Card modifications info

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_button.scss
- app/assets/stylesheets/components/_filters.scss
- app/assets/stylesheets/components/_map.scss
- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/components/_sport_session_card.scss
- app/assets/stylesheets/config/_responsive.scss
- app/javascript/channels/sport_session_channel.js
- app/views/layouts/application.html.erb
- app/views/shared/_navbar.html.erb
- app/views/shared/_search_filters.html.erb
- app/views/sport_sessions/_info_window.html.erb
- app/views/sport_sessions/show.html.erb
> create responsive navbar
> create responsive filters
> create responsive show
> Responsive

- app/assets/stylesheets/components/_banner_video.scss
- app/views/shared/_banner_video.html.erb
Change hp video from youtube embed to html5 <video> tag (hosted on cloudinary)
> Make hp video autoplay on mobile
